const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    FETCH_GENDERS_SUCCESS: 'FETCH_GENDERS_SUCCESS',
    FETCH_GENDERS_FAIL: 'FETCH_GENDERS_FAIL',

    FETCH_ROLES_SUCCESS: 'FETCH_ROLES_SUCCESS',
    FETCH_ROLES_FAIL: 'FETCH_ROLES_FAIL',

    FETCH_NOTIFICATIONS_SUCCESS: 'FETCH_NOTIFICATIONS_SUCCESS',
    FETCH_NOTIFICATIONS_FAIL: 'FETCH_NOTIFICATIONS_FAIL',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_AUTHENTICATE: 'USER_AUTHENTICATE',
});

export default actionTypes;
